I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1626, in script
    $ control_room_tries += 1
  File "game/script.rpy", line 1626, in <module>
    $ control_room_tries += 1
NameError: name 'control_room_tries' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1626, in script
    $ control_room_tries += 1
  File "C:\Users\alext\OneDrive - Universidade de Lisboa\Documentos\Programas\renpy-8.0.0-sdk\renpy\ast.py", line 1111, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\alext\OneDrive - Universidade de Lisboa\Documentos\Programas\renpy-8.0.0-sdk\renpy\python.py", line 1049, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 1626, in <module>
    $ control_room_tries += 1
NameError: name 'control_room_tries' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.0.22062402
SuNoFes 22 1.0
Wed Aug 31 23:36:57 2022
